# Generated by Django 2.0 on 2018-12-02 18:20

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181202_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body3',
            field=wagtailmd.utils.MarkdownField(blank=True, null=True),
        ),
    ]
