# Generated by Django 2.1.4 on 2018-12-14 06:09

from django.db import migrations
import wagtailmd.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_portfoliopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='body2',
            field=wagtailmd.utils.MarkdownField(blank=True, null=True),
        ),
    ]
